require('aerial').setup({
  attach_mode = "global",
  placement = "edge",
  backends = { "lsp", "treesitter", "markdown", "man" },
  default_direction = "prefer_right",
  layout = { width = 35 },
  show_guides = true,
  filter_kind = false,
  guides = {
    mid_item = "├ ",
    last_item = "└ ",
    nested_top = "│ ",
    whitespace = "  ",
  },
  icons = {
    Array         = " ",
    Boolean       = " ",
    Class         = " ",
    Collapsed     = " ",
    Constant      = " ",
    Constructor   = " ",
    Enum          = " ",
    EnumMember    = " ",
    Event         = " ",
    Field         = "ﰠ ",
    File          = " ",
    Function      = " ",
    Interface     = " ",
    Key           = " ",
    Method        = "ƒ ",
    Module        = " ",
    Namespace     = " ",
    Null          = " ",
    Number        = " ",
    Object        = " ",
    Operator      = " ",
    Package       = " ",
    Property      = " ",
    String        = " ",
    Struct        = "פּ ",
    TypeParameter = " ",
    Variable      = " ",
  },
})
