return {
  cmp = {
    Class         = "",
    Color         = "",
    Constant      = "",
    Constructor   = "",
    Enum          = "",
    EnumMember    = "",
    Event         = "",
    Field         = "ﰠ",
    File          = "",
    Folder        = "",
    Function      = "",
    Interface     = "",
    Keyword       = "",
    Method        = "ƒ",
    Module        = "",
    Operator      = "",
    Property      = "",
    Reference     = "",
    Snippet       = "",
    Struct        = "פּ",
    Text          = "",
    TypeParameter = "",
    Unit          = "",
    Value         = "",
    Variable      = "",

    Array         = " ",
    Boolean       = " ",
    Collapsed     = " ",
    Key           = " ",
    Namespace     = " ",
    Null          = " ",
    Number        = " ",
    Object        = " ",
    Package       = " ",
    String        = " ",
    Comment       = "󰅺",

    VariableBuiltin  = "",
  }
}
