require('mansur/telescope')
require('mansur/lualine')
require('mansur/git-signs')
require('mansur/nvimtree')
require('mansur/barbar')
require('mansur/dashboard')
require('mansur/lsp')
require('mansur/cmp-setup')
require('mansur/treesitter')
require('mansur/floaterm')
require('mansur/comment')

