require('mansur/keymaps')
require('mansur/clipboard')
require('mansur/highlight')
require('mansur/telescope')
require('mansur/lualine')
require('mansur/git-signs')
require('mansur/nvimtree')
-- require('mansur/neotree')
require('mansur/barbar')
-- require('mansur/dashboard')
require('mansur/lsp')
require('mansur/cmp-setup')
require('mansur/comment')
require('mansur/hop')
require('mansur/treesitter')
-- require('mansur/registers')
require('mansur/toggleterm')
require('mansur/indent-blankline')
require('mansur/autopairs')
require('mansur/whichkey')
require('mansur/filetypes')
